---
title: "R Notebook"
output: html_notebook
---

NFL Viz

```{r}
library(tidyverse)
library(nflfastR)
library(ggrepel) 
library(ggimage)
library(ggthemes)
library(na.tools)
library(gt)
```

### Misc
```{r}
nflreadr::load_snap_counts(2021)
nflfastR::load_ngs(2021, "passing")
```

```{r}
#creating our own theme
theme_reach <- function() {
  theme_fivethirtyeight() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 20, hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    axis.title.x = element_text(size=14),
    axis.title.y = element_text(size=14)
  )
}
```

### Snap Counts
```{r}
#Snap Counts
nflreadr::load_snap_counts(2021) %>%
select(pfr_id, game_id, ends_with(c("snaps", "pct"))) %>%
left_join(nflreadr::load_rosters(2021), by = "pfr_id") %>%
filter(team == "PHI", position %in% c("RB", "WR", "TE")) %>%
select(full_name, position, offense_snaps, offense_pct, defense_snaps, defense_pct)
```

### QB after being pressured
```{r}
future::plan("multisession")
pbp <- nflfastR::load_pbp(2018:2020)

pbp_pressure <- pbp %>%
  filter(pass == 1 | rush == 1) %>%
  group_by(game_id, posteam) %>%
  mutate(hit_prev_play = lag(qb_hit))

passer_teams <- pbp %>%
  group_by(passer, posteam) %>%
  summarise(plays = n()) %>%
  top_n(1) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

passers <- pbp_rp %>%
  filter(!is.na(passer)) %>%
  filter(hit_prev_play == 1) %>%
  group_by(passer) %>%
  summarise(pres_passes = n(),
            ypa = mean(air_yards, na.rm = TRUE),
            epa = mean(epa, na.rm = TRUE)) %>%
  filter(pres_passes >= 30) %>%
  left_join(passer_teams, by = c("passer"))

passers %>%
  ggplot(aes(x = epa, y = ypa)) +
  geom_point(aes(size = pres_passes, fill = team_color, color = team_color2), shape = 21) +
  ggrepel::geom_text_repel(aes(label = passer), size = 4, box.padding = 0.20) +
  theme_reach() +
  geom_hline(yintercept = mean(passers$ypa), linetype = "dashed", alpha = 0.5) +
  geom_vline(xintercept = mean(passers$epa), linetype = "dashed", alpha = 0.5) +
  scale_size(name = "Passes After Pressure") +
  scale_color_identity(aesthetics = c("fill", "color")) +
  labs(x = "EPA After Pressure", 
       y = "Yard Per Attempt After Pressured",
       title = "How Quarterbacks Perform on Plays After Being Pressured",
       subtitle = "2018-2020, minimum of 30 passes after being pressured, bubble size is sample size",
       caption = "@becausejustyn") +
  scale_x_continuous(breaks = pretty_breaks(n = 10)) +
  scale_y_continuous(breaks = pretty_breaks(n = 10))

ggsave('pressure.png', width = 15, height = 10, dpi = "retina")
```

### Huh
```{r}
future::plan("multisession")
pbp <- nflfastR::load_pbp(2018:2020)

pbp <- pbp %>%
  filter(!is.na(epa)) %>%
  filter(!is.na(passer))

non_gb_time <- pbp %>%
  filter(qb_dropback == 1) %>%
  filter(wp > 0.05 & wp < 0.95) %>%
  group_by(passer) %>%
  summarise(non_gb_passes = n(),
            epa_per_db = mean(epa))

gb_time <- pbp %>%
  filter(qb_dropback == 1) %>%
  filter(wp > 0.05 & wp < 0.95) %>%
  group_by(passer) %>%
  summarise(gb_passes = n(),
            gb_epa = mean(epa))

player_teams <- pbp %>%
  group_by(passer, posteam) %>%
  summarise(snaps = n()) %>%
  top_n(1) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

all_time <- non_gb_time %>%
  left_join(gb_time, by = c("passer")) %>%
  left_join(player_teams, by = c("passer")) %>%
  arrange(desc(snaps)) %>%
  slice_head(n = 40)

all_time %>%
  ggplot() +
  geom_smooth(aes(x = epa_per_db, y = gb_epa), method = "lm", color = "grey", se = FALSE) +
  ggrepel::geom_text_repel +
  geom_point() +
  geom_hline(yintercept = mean(all_time $gb_epa), color = "black", linetype = "dashed", alpha = 0.5) +
  geom_vline(xintercept = mean(all_time$epa_per_db), linetype = "dashed", alpha = 0.5) +
  scale_size(name = "Dropbacks") +
  scale_color_identity(aesthetics = c("fill", "color")) +
  theme_reach() +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  labs(x = "Non-Garbage Time EPA/Dropback", 
    y = "Garbage Time EPA/Dropback",
    title = "How Quarterbacks Performed in and out of Garbage Time, 2018-2020",
    subtitle = "minimum of 600 dropbacks, garbage time is when win probability is >= 95% or <= 5%",
    caption = "@becausejustyn")

ggsave('garbage-time.png', width = 14, height = 10, dpi = "retina")
```



### Yoo

```{r}
pbp <- nflfastR::load_pbp(2020)

pbp_rp <- pbp %>%
  filter(!is.na(epa)) %>%
  filter(rush == 1 | pass == 1)

teams <- pbp_rp %>%
  group_by(posteam, pass) %>%
  summarize(epa = mean(epa))

teams %>%
  group_by(pass) %>%
  summarize(league_avg = mean(epa))

browns <- pbp_rp %>%
  filter(posteam == "CLE")

browns_rec <- browns %>%
  filter(!is.na(receiver_player_name)) %>%
  group_by(def) %>%
  summarize(targets = n(),
            completion_rate = mean(complete_pass),
            adot = mean(air_yards, na.rm = T),
            yac = mean(yards_after_catch, na.rm = T),
            epa = mean(epa)) %>%
  filter(targets >= 10)

pbp_rp <- pbp_rp %>%
  mutate(yards_past_sticks = air_yards - ydstogo)

afc_north <- c("CLE", "PIT", "CIN", "BAL")

yps <- pbp_rp %>%
  filter(!is.na(yards_past_sticks)) %>%
  filter(down %in% c(2, 3)) %>%
  group_by(posteam) %>%
  summarize(avg_yps = mean(yards_past_sticks),
            yps_rate = 100*mean(yards_past_sticks >= 0),
            yac = mean(yards_after_catch, na.rm = T)) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

yps %>%
  ggplot(aes(x = avg_yps, y = yac)) +
  geom_smooth(method = "lm", color = "black", size = 2) +
  geom_hline(yintercept = mean(yps$yac), linetype = "dashed") +
  geom_vline(xintercept = mean(yps$avg_yps), linetype = "dashed") +
  geom_image(aes(image = team_logo_espn), asp = 16/9, size = 0.05) +
  theme_bw() +
  labs(x = "Average Yards Past Sticks",
       y = "Average YAC",
       title = "Each Team's Yards Past Sticks and YAC on 2nd and 3rd Down",
       subtitle = "2020 only")
```




## Stafford

```{r}
library(ggimage)

future::plan("multisession")
pbp <- nflfastR::load_pbp(2009:2021)

stafford_games <- pbp %>%
  filter(qb_dropback == 1) %>%
  filter(passer_player_name, defteam, season, week, posteam) %>%
  summarise(passes = n(),
            adot = mean(air_yards, na.rm = TRUE),
            epa = mean(epa, na.rm = TRUE),
            cpoe = mean(cpoe, na.rm = TRUE)) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr")) %>%
  mutate(game_label = paste0(season, ", ", posteam, " vs. ", defteam)) %>%
  arrange(-epa) %>%
  ungroup() %>%
  mutate(rank = row_number()) %>%
  filter(rank <= 15)

stafford_games %>%
  ggplot(aes(x = epa, y = fct_reorder(game_label, epa))) +
  geom_bar(aes(fill = team_color, color = team_color2), stat = "identity", alpha = 0.9) +
  geom_image(aes(x = epa + 0.03, image = team_logo_espn), asp = 16/9, size = 0.045) +
  scale_color_identity(aesthetics = c("fill", "color")) +
  theme_reach() +
  labs(x = "AEPA/Dropback",
       y = "Game",
       title = "Matthew Stafford's Top-15 Games According to EPA/Dropback",
       caption = "@becausejustyn")
```

## How QB Pass in Pure Passing Sitations

```{r}
future::plan("multisession")
pbp <- nflfastR::load_pbp(2009:2021)

qb_colours <- pbp %>%
  group_by(passer_player_name, posteam) %>%
  summarise(passes = n()) %>%
  arrange(-passes) %>%
  group_by(passer_player_name) %>%
  top_n(n = 1) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

pbp_xp <- pbp %>%
  filter(qb_dropback == 1) %>%
  filter(xpass > 0.7) %>%
  filter(!is.na(passer_player_name)) %>%
  group_by(passer_player_name) %>%
  summarise(plays = n(),
            mean_epa = mean(epa, na.rm = TRUE)) %>%
  left_join(qb_colours, by = c("passer_player_name")) %>%
  filter(plays >= 400)

pbp_xp %>%
  ggplot(aes(x = mean_xpa, y = fct_reorder(passer_player_name, mean_epa))) +
  geom_bar(aes(fill = team_color, color = team_color2), alpha = 0.9, stat = "identity") +
  geom_image(aes(x = -0.16, image = team_logo_espn), asp = 16/9, size = 0.025) +
  scale_color_identity(aesthetics = c("fill", "color")) +
  theme_reach() +
  labs(x = "EPA/Dropback in Pure Passing Situations",
       y = "",
       title = "How Quarterbacks Perform in Pure Passing Situations, 2018-2021",
       subtitle = "Minimum of 400 plays when expected pass % was greater than 70%",
       caption = "@becausejustyn")
```

```{r}
library(bayesboot)

# Read and mutate data
seasons <- 2016:2020
pbp_i <- purrr::map_df(seasons, function(x) {
  readRDS(
    url(
      glue::glue("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_{x}.rds")
    )
  )
})

#Prepare data frame
pbp = pbp_i %>% 
filter(
  season_type == 'REG',
  play_type %in% c('pass'),
  !is.na(epa),
  !is.na(name)
) %>% 
  group_by(passer_player_id) %>%
  mutate(
    num_plays = n()
  ) %>% 
  ungroup() %>%
  filter(
    num_plays >= 120
  )


#Bootstrapping
#Here you will use your data and RYOE instead of EPA
lst = list()
qbs = unique(pbp$name)
for (qb in qbs){
  pbp_qb = pbp %>% filter(name == qb)
  b <- bayesboot(as.vector(pbp_qb$epa), mean)
  s = summary(b)
  mean_epa = s$value[1]
  lci = s$value[3]
  uci = s$value[4]
  df = data.frame('mean'=mean_epa,'LCI'=lci,'UCI'=uci)
  lst[[qb]] = df
}
df = dplyr::bind_rows(lst)
df$QB = qbs
df = df %>% arrange(mean)

#Plot
#This is the basic, the rest in terms of aesthetics and 
#fancy stuff is up to you!
 
df %>%
  ggplot(aes(x=factor(QB, level = QB),y=mean)) + 
  geom_pointrange(aes(ymin=(LCI),
                      ymax=(UCI)))+
  coord_flip()+
  theme_bw() + ggsave('plot1.png',height = 8, width = 10)


#You can do a whole lot of things with this code for example:
lst = list()
qbs = c('D.Prescott','J.Goff','C.Wentz')
for (qb in qbs){
  pbp_qb = pbp %>% filter(name == qb)
  b <- bayesboot(as.vector(pbp_qb$epa), mean)
  df = data.frame('estimate'=b$V1,'QB'=qb,team_abbr  = unique(pbp_qb$posteam))
  lst[[qb]] = df
}

df = dplyr::bind_rows(lst)
colors = nflfastR::teams_colors_logos %>% filter(team_abbr %in% c('DAL','LA','PHI'))

df %>% ggplot(aes(x=estimate)) +
  geom_density(aes(fill=QB),alpha=.6)+
  scale_fill_manual(
    values = c(colors$team_color[3],colors$team_color[1],colors$team_color2[2])
  ) + theme_bw() + 
  theme(
    plot.title = element_text(size=14),
    plot.subtitle = element_text(size=13),
    axis.title.y =element_blank() )+
  labs(
    title = 'Bayesian Bootstrapping to estimate range of possible outcomes for QB class of 2016.',
    subtitle = 'Regular Season. 2016 - 2020. Passing plays only.',
    x = 'Passing Efficiency'
  )
```

```{r}
#cleans the data
pbp_rp <- pbp %>% filter(pass==1 | rush==1)

#get offensive stats
team_off <- pbp_rp %>%
  filter(!is.na(yards_gained)) %>% #filters out any plays that are missing data
  group_by(posteam) %>% #groups each of the 32 teams
  summarize(off_ypp = mean(yards_gained)) #gets the average yards gained per play

#get defensive stats
team_def <- pbp_rp %>%
  filter(!is.na(yards_gained)) %>% 
  group_by(defteam) %>%
  summarize(def_ypp = mean(yards_gained))

#joining the offensive and defensive stats together
teams <- team_off %>%
  left_join(team_def, by = c("posteam" = "defteam"))

#adding in team colors and logos
teams <- teams %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

teams %>%
  ggplot(aes(x = off_ypp, y = def_ypp)) +
  #horizontal line with mean off_ypp
  geom_hline(yintercept = mean(teams$off_ypp), color = "blue", linetype = "dashed", alpha=0.5) +
  #vertical line with mean def_ypp
  geom_vline(xintercept =  mean(teams$def_ypp), color = "blue", linetype = "dashed", alpha=0.5) +
  #add the logos onto the plot
  geom_image(aes(image = team_logo_espn), size = 0.05, asp = 16 / 9) +
  #adding on labels
  labs(x = "Offensive Yards Per Play",
       y = "Defensive Yards Per Play",
       title = "NFL Teams Yards Per Play in 2020",
       caption = "Data: nflfastR") +
  theme_reach() +
  scale_y_reverse(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))

ggsave('nfl_ypp.png', width = 14, height = 10, dpi = 300) #saving your graph
```

```{r}
#now let's see which teams have the biggest difference between their passing and running
pass_stats <- pbp_rp %>%
  filter(!is.na(yards_gained)) %>% 
  filter(!is.na(pass_oe)) %>%
  filter(pass == 1) %>%
  group_by(posteam) %>%
  summarize(pass_ypp = mean(yards_gained)) 

run_stats <- pbp_rp %>%
  filter(!is.na(yards_gained)) %>% 
  filter(rush == 1) %>%
  group_by(posteam) %>% 
  summarize(run_ypp = mean(yards_gained))

#this time since we did group_by with posteam both times it'll join automatically
pass_run_stats <- pass_stats %>%
  left_join(run_stats)

pass_run_stats <- pass_run_stats %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

pass_run_stats <- pass_run_stats %>%
  mutate(pass_minus_run = pass_ypp - run_ypp) %>% #mutate makes a new column
  arrange(desc(pass_minus_run)) %>% #putting the teams with the biggest diff at the top
  mutate(rank = row_number())

tab_data <- pass_run_stats %>%
  select(rank, team_wordmark, pass_ypp, run_ypp, pass_minus_run)

tab_data <- tab_data %>%
  mutate_if(is.numeric, ~round(., 1))

ypp_diff <- tab_data %>% 
  gt() %>% 
  text_transform(
    locations = cells_body(vars(team_wordmark)),
    fn = function(x){
      web_image(
        url = x,
        height = px(20)
      )
    }
  ) %>% 
  cols_label(
    rank = "Rank",
    team_wordmark = "Team",
    pass_ypp = "Pass YPP",
    run_ypp = "Rush YPP",
    pass_minus_run = "Diff.") %>%
  data_color(
    columns = vars(pass_minus_run),
    colors = scales::col_numeric(
      palette = c("#af8dc3", "#f7f7f7", "#7fbf7b"),
      domain = c(0, 3.5)
    )
  ) %>% 
  tab_header(
    title = "Each Team's Difference Between Pass and Rush YPP",
    subtitle = "YPP = Yards per Play"
  ) %>%
  tab_options(
    column_labels.background.color = "white",
    column_labels.font.weight = "bold",
    table.border.top.width = px(3),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    column_labels.border.top.width = px(3),
    column_labels.border.top.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    data_row.padding = px(3),
    source_notes.font.size = 12,
    table.font.size = 16,
    heading.align = "middle",
  ) %>%
  opt_table_font(
    font = list(
      default_fonts()
    )
  ) 
```

### Clustering

```{r}
library(stats)
library(mclust)
library(mdthemes)
library(gghighlight)
library(ggsci) 
library(broom)
library(igraph)

X <- pass_run_stats %>%
  select(pass_ypp, run_ypp, pass_minus_run)

set.seed(222) # set seed to ensure reproduceability b/c k-means relies on random states for initialization 
MAX_K <- 20 # max number of clusters
sse <- c() # vector to hold SSE of each model

for (k in 1:MAX_K) {
  algo_k <- kmeans(X, centers=k, nstart=22, iter.max=20) # k-means algorithm
  sse <- c(sse, algo_k$tot.withinss) # get SSE
} 

#seeing the rolling SEE
tibble(k = 1:MAX_K, SSE_difference = sse-2*lead(sse)+lead(sse, 2)) %>%
  dplyr::filter(k<MAX_K-1) %>%
  ggplot(aes(x=k, y=SSE_difference)) + 
  geom_point(color="#F84C1E") + geom_line(color="#232D4B") + 
  labs(x = "K", y = "SSE Rolling 2-Unit Difference", title = "A Clear Picture") + 
  scale_x_continuous(breaks=seq(1, MAX_K, 1)) + 
  theme_minimal() + theme_reach() + 
  theme(panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank())

#we should create 4 clusters because that's where it really levels off

set.seed(22)
# re-run K-Means with 4 clusters
K <- 4
kmeans4 <- kmeans(X, centers=K, nstart=22, iter.max=20)
km_centers <- as.data.frame(kmeans4$centers) # SCALED cluster centers/means

km_centers$Cluster <- c('Cluster 1', 'Cluster 2', 'Cluster 3',
                        'Cluster 4') 

km_centers <- km_centers %>%
  rename(c('PYPP'='pass_ypp', 'RYPP'='run_ypp', # give predictors a shorter name for plotting
           'DIFF'='pass_minus_run')) %>% 
  pivot_longer(!Cluster, names_to = 'feature', values_to = 'z_val') # pivot data to make plotting easier

team_clusters <- tibble(cluster=kmeans4$cluster, team=pass_run_stats$posteam)

km_centers %>% 
  ggplot(aes(x=feature, y=z_val, color=Cluster)) + 
  geom_point() + # plot points
  scale_color_brewer(palette="Paired") + # color points
  gghighlight(use_direct_label = FALSE) + # highlight each cluster
  facet_wrap(~ Cluster, ncol=2) + # create seperate plots for each cluster
  labs(x = "Predictor", y = "Cluster Center", 
       title = "Visualizing K-Means Cluster Makeups") + 
  theme_minimal() + theme_reach() + 
  theme(legend.position = "none", strip.text = element_text(face='bold'),
        axis.text.x = element_text(angle=90, size=8), # alter axis text
        panel.grid.minor = element_blank())  

#cluster 1 has the lowest difference and rember how philly was in the bottom of our plot!

team_clusters <- team_clusters %>%
  left_join(pass_run_stats, by = c("team" = "posteam"))

team_clusters %>%
  ggplot(aes(x = pass_ypp, y = run_ypp)) +
  geom_hline(yintercept = mean(team_clusters$run_ypp), color = "blue", linetype = "dashed", alpha=0.5) +
  geom_vline(xintercept =  mean(team_clusters$pass_ypp), color = "blue", linetype = "dashed", alpha=0.5) +
  geom_point(size = 3, color = team_clusters$cluster, alpha = .8) +
  #add names using ggrepel, which tries to make them not overlap
  geom_text_repel(aes(label=team)) +
  #add a smooth line fitting cpoe + epa
  stat_smooth(geom='line', alpha=0.5, se=FALSE, method='lm')+
  #titles and caption
  labs(x = "Pass YPP",
       y = "Rush YPP",
       title = "Clustering Analysis of the YPP of NFL Teams",
       caption = "By Tej Seth") +
  #uses the black and white ggplot theme
  theme_reach() +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))
```

