---
title: "R Notebook"
output: html_notebook
---

## Loading Libraries, Data

```{r libraries, reading data}
library(beeswarm) 
library(ggbeeswarm)
library(tidyverse)
library(scales)

pbp <- purrr::map_df(c(2001:2021), function(x) {
  readRDS(
      glue::glue("~/Documents/nfl/data/pbp/play_by_play_{x}.rds")
    )
}) %>%
  filter(season_type == 'REG')
```

## Wrangling the Data

### Play Count By Team, Season, Down
```{r}
df <- pbp %>%
  filter(down == 4, ydstogo <= 4, play_type %in% c("field_goal", "pass", "punt", "run")) %>%
  group_by(posteam, season, ydstogo) %>%
  count(play_type) %>%
  ungroup()
```

### Wide Version
```{r}
df_wide <- df %>%
  spread(play_type, n) %>%
  group_by(posteam, season, ydstogo) %>%
  mutate(
    opportunities = sum(c_across(field_goal:run), na.rm = TRUE),
    go_for_it_n = sum(pass, run, na.rm = TRUE),
    go_for_it_rate = go_for_it_n / opportunities
  ) %>%
  ungroup()
```

### Team By Season
```{r}
df_wide_season <- df_wide %>%
  group_by(posteam, season) %>%
  summarise(
    field_goal = sum(field_goal, na.rm = TRUE),
    pass = sum(pass, na.rm = TRUE),
    punt = sum(punt, na.rm = TRUE),
    run = sum(run, na.rm = TRUE),
    opportunities = sum(c_across(field_goal:run), na.rm = TRUE),
    go_for_it_n = sum(pass, run, na.rm = TRUE),
    go_for_it_rate = go_for_it_n / opportunities,
    .groups = "drop"
  ) %>%
  left_join(select(nflfastR::teams_colors_logos, posteam = team_abbr, team_color, team_color2))
```

### Team Overall
```{r}
df_wide_team <- df_wide_season %>%
  select(-c(season, team_color, team_color2)) %>%
  group_by(posteam) %>%
  summarise(
    across(everything() & !c(go_for_it_n, go_for_it_rate), sum, .names = "total_{.col}"), .groups = "keep") %>%
  mutate(
    total_go_for_it = sum(total_pass, total_run, na.rm = TRUE),
    go_for_it_rate = total_go_for_it / total_opportunities
  ) %>%
  ungroup() %>%
  left_join(select(nflfastR::teams_colors_logos, posteam = team_abbr, team_color, team_color2))
```

## Viz

### League Wide Go For It Rate

```{r}
df_wide_season %>% 
  ggplot(aes(
    x = season, 
    y = go_for_it_rate, 
    fill = go_for_it_rate
    )) + 
  geom_quasirandom(pch = 21, size = 3) + 
  scale_fill_viridis_c("",  guide = 'none', option = 'E') + 
  scale_x_continuous(labels = 2001:2021, breaks = 2001:2021) + 
  scale_y_continuous(labels = scales::percent) + 
  labs(title = "Go-for-it rate, 4th-4 or less", y = "", x = "") +
  hrbrthemes::theme_ft_rc()
```

### Mean Go For It Rate

I did this without doing a summary df just so I could get practice how to do it via ggplot2()

```{r}
df_wide_season %>%
  ggplot(aes(
    x = forcats::fct_reorder(.f = posteam, .x = go_for_it_rate, .fun = mean),
    fill = team_color2,
    colour = team_color,
    y = go_for_it_rate,
    group = posteam
  )) +
  geom_bar(stat = "summary", fun = mean) +
  #geom_text(aes(label = sum(n_chances)), stat = 'unique') +
  coord_flip(ylim = c(0.22, 0.31)) +
  #coord_flip(ylim = c(0.225, 0.325)) +
  #scale_y_continuous(breaks = seq(0.225, 0.325, 0.025)) +
  scale_y_continuous(n.breaks = 8) +
  scale_color_identity(aesthetics = c('fill', 'colour')) +
  hrbrthemes::theme_ft_rc(base_size = 9.5, axis_title_size = 11) +
  labs(
    y = 'Go For It Rate',
    x = 'Team',
    title = 'Go For it Rate',
    subtitle = '2001 - 2021, Regular Season',
    caption = '4th down and 4 yards or less. data: nflfastR'
  )
```

### Mean Go For It Rate w/ Text

```{r}
df_wide_team %>%
  ggplot(aes(
    x = fct_reorder(posteam, go_for_it_rate),
    y = go_for_it_rate,
    fill = team_color,
    colour = team_color2
  )) +
  geom_col() +
  geom_text(aes(y = 0.2175, label = total_opportunities), stat = 'unique') +
  geom_text(aes(label = round(go_for_it_rate, 3)), stat = 'unique', hjust = 1.15) +
  coord_flip(ylim = c(0.22, 0.31)) +
  scale_y_continuous(
    n.breaks = 8,
    labels = label_number(accuracy = 1, scale = 100, suffix = '%')
  ) +
  scale_color_identity(aesthetics = c('fill', 'colour')) +
  hrbrthemes::theme_ft_rc(base_size = 9.5, axis_title_size = 11) +
  labs(
    y = 'Go For It Rate',
    x = 'Team',
    title = 'Go For it Rate',
    subtitle = '2001 - 2021, Regular Season',
    caption = '4th down and 4 yards or less. data: nflfastR\n Number of the left is the n of chances.'
  )
```

