---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidymodels)
library(nflfastR)
library(gghighlight)
library(ggrepel)

pbp <- read_rds("~/Documents/nfl/data/pbp/play_by_play_2021.rds")
```

# Simple Clustering

This will only have 3 numerical values. Rush yards per play, pass yards per play, difference

```{r}
df <- pbp %>%
  mutate(yards_past_sticks = air_yards - ydstogo)

pass_stats <- df %>%
  filter(
    !is.na(yards_gained), !is.na(pass_oe), pass == 1) %>% 
  group_by(posteam) %>%
  summarise(pass_ypp = mean(yards_gained)) 

run_stats <- df %>%
  filter(
    !is.na(yards_gained), rush == 1) %>% 
  group_by(posteam) %>% 
  summarise(run_ypp = mean(yards_gained))

# since we did group_by() with `posteam` both times it'll join automatically
pass_run_stats <- pass_stats %>%
  left_join(run_stats)

pass_run_stats <- pass_run_stats %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

pass_run_stats <- pass_run_stats %>%
  mutate(pass_minus_run = pass_ypp - run_ypp) %>% 
  arrange(-pass_minus_run) %>% #putting the teams with the biggest diff at the top, desc() inside the arrange function also works
  mutate(rank = row_number())
```

```{r}
pass_run_scaled <- pass_run_stats %>%
  mutate(across(contains(c('_ypp', 'pass_minus')), ~ as.numeric(scale(.))))

kclusts <- tibble(k = 1:9) %>%
  mutate(
    kclust = purrr::map(k, ~ kmeans(select(pass_run_scaled, contains(c('_ypp', 'pass_minus'))), .x)),
    glanced = purrr::map(kclust, glance),
  )

kclusts %>%
  unnest(cols = c(glanced)) %>%
  ggplot(aes(k, tot.withinss)) +
  geom_line(alpha = 0.5, size = 1.2, color = "midnightblue") +
  geom_point(size = 2, color = "midnightblue") +
  scale_x_continuous(breaks = seq(1, 9, 1))

kclusts %>%
  unnest(cols = c(glanced)) %>%
  mutate(
    sse_difference = rolling_see_difference(tot.withinss)
  ) %>%
  ggplot(aes(
    x = k, 
    y = sse_difference)) +
    geom_line(alpha = 0.5, size = 1.2, color = "midnightblue") +
    geom_point(size = 2, color = "midnightblue") +
    scale_x_continuous(breaks = seq(1, 9, 1)) +
    labs(
      x = "k",
      y = "SSE Rolling 2-Unit Difference"
    )
```

```{r}
#4 seems like a fun idea
set.seed(2017)
final_clust <- kmeans(select(pass_run_scaled, contains(c('_ypp', 'pass_minus'))), centers = 5)

clust_cen <- final_clust %>% 
  augment(pass_run_scaled) 
#paste0("Cluster ", c(1:5)) 
```

```{r}
clust_cen_long <- clust_cen %>%
  select(where(is.numeric), .cluster, -rank) %>%
  rename(c(
    'Pass YPP' = 'pass_ypp',
    'Rush YPP' = 'run_ypp', 
    'Pass Minus Rush' = 'pass_minus_run'
  )) %>% 
  # pivot data to make plotting easier
  pivot_longer(
    !.cluster, 
    names_to = 'feature', 
    values_to = 'z_val') 

team_clusters <- select(clust_cen, posteam, .cluster)
```


```{r}
clust_cen_long %>% 
  ggplot(aes(
    x = feature, 
    y = z_val, 
    colour = .cluster)) + 
  geom_point() + 
  scale_color_brewer(palette = "Paired") + 
  gghighlight(use_direct_label = FALSE) + 
  facet_wrap(~ .cluster, ncol=2) + 
  labs(
    x = "Predictor", 
    y = "Cluster Center",
    title = "Visualizing K-Means Cluster Makeups") + 
  becausejustynfun::white_theme() +
  theme(
    legend.position = "none", 
    strip.text = element_text(face='bold'),
    axis.text.x = element_text(angle = 90, size = 8), # alter axis text
    panel.grid.minor = element_blank())  
```

```{r}
team_clusters <- team_clusters %>%
  left_join(pass_run_stats)

team_clusters %>%
  ggplot(aes(
    x = pass_ypp, 
    y = run_ypp)) +
  geom_hline(aes(yintercept = mean(run_ypp)), colour = "blue", linetype = "dashed", alpha = 0.5) +
  geom_vline(aes(xintercept =  mean(pass_ypp)), colour = "blue", linetype = "dashed", alpha = 0.5) +
  geom_point(aes(color = .cluster), size = 3, alpha = .8) +
  scale_color_manual(values = c('#009392', '#9ccb86', '#eeb479', '#B86C70', '#88CCEE')) +
  geom_text_repel(aes(label = posteam), colour = team_clusters$team_color) +
  #add a smooth line fitting cpoe + epa
  stat_smooth(geom = 'line', alpha = 0.5, se = FALSE, method = 'lm') +
  #titles and caption
  labs(
    x = "Pass YPP",
    y = "Rush YPP",
    title = "Clustering Analysis of the YPP of NFL Teams",
    caption = "By me") +
  #uses the black and white ggplot theme
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  becausejustynfun::white_theme() 
```


