---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

pbp <- read_rds("~/Documents/nfl/data/pbp/play_by_play_2021.rds") %>%
  filter(season_type == 'REG') %>%
  filter(
    special == 0 & 
      special_teams_play == 0 & 
      is.na(st_play_type) & 
      !play_type %in% NA
    ) %>% 
  select(
    game_id, week, posteam, yardline_100, down, 
    ydstogo, ydsnet, play_type, play_type_nfl, 
    pass, rush, yards_gained, pass_length, pass_location, 
    fourth_down_converted, fourth_down_failed, first_down, 
    xpass, pass_oe, run_gap, run_location)
```

# Pass Rate Over Expected

```{r pass_oe_df}
pass_oe <- pbp %>%
  filter(!is.na(pass_oe)) %>%
  group_by(posteam) %>%
  summarise(
    pass_oe = mean(pass_oe),
    xpass = mean(xpass),
    pass = mean(pass)
  ) %>% 
  left_join(
    nflfastR::teams_colors_logos %>% 
      select(team_abbr, team_color, team_color2, team_color3, team_color4), 
    by = c("posteam" = "team_abbr"))

#pass_oe %>% summarise(across(c(pass_oe:pass), range)) #ranges for plotting

pass_oe_plot <- pass_oe %>%
  ggplot() +
  geom_col(
    aes(x = pass_oe, y = fct_reorder(posteam, pass_oe),
        fill = team_color, colour = team_color2), alpha = 0.6, width = 0.9, size = 0.5
  ) +
  scale_x_continuous(breaks = seq(-8, 10, 1)) + 
  coord_cartesian(xlim = c(-8, 10)) +
  scale_color_identity(aesthetics = c('fill', 'colour')) +
  hrbrthemes::theme_ft_rc(base_size = 9.5, axis_title_size = 11) +
  labs(
    x = '',
    y = '',
    title = 'Pass Rate Over Expected by Team',
    subtitle = '2021, Regular Season',
    caption = 'data: nflfastr'
  )
```

```{r pass_oe_plot}
pass_oe_plot
```
