---
title: "R Notebook"
output: html_notebook
---

Scheme

```{r}
pbp <- purrr::map_df(c(2016:2021), function(x) {
  readRDS(
      glue::glue("~/Documents/nfl/data/pbp/play_by_play_{x}.rds")
    )
})

rosters <- purrr::map_df(c(2016:2021), function(x) {
  readRDS(
      glue::glue("~/Documents/nfl/data/roster/roster_{x}.rds")
    )
})
```

### Snap Counts

```{r}
#Snap Counts
snap_count_2021 <- nflreadr::load_snap_counts(2021)

snap_count_2021_df <- snap_count_2021 %>%
  filter(game_type == 'REG') %>%
  select(pfr_player_id, week, game_id, ends_with(c("snaps", "pct"))) %>%
  left_join(filter(rosters, season == 2021), by = c("pfr_player_id" = "pfr_id")) %>%
  filter(team == "PHI", position %in% c("RB", "WR", "TE")) %>%
  select(full_name, position, week, offense_snaps, offense_pct, defense_snaps, defense_pct)

phi_colours <- teams_colors_logos %>%
  filter(team_abbr == 'PHI')
```

```{r}
snap_count_2021_df %>%
  filter(!full_name %in% c("Noah Togiai", "Jason Huntley", "Richard Rodgers", "John Hightower")) %>%
 ggplot(aes(
   x = week, 
   y = offense_pct
   )) +
  geom_col(aes(fill = phi_colours$team_color, colour = phi_colours$team_color2)) +
  scale_x_continuous(breaks = seq(1, 18, 3)) +
  scale_color_identity(aesthetics = c('fill', 'colour')) +
  labs(
    x = '',
    y = 'Offense Snap Percent',
    title = 'Eagles Offense Snap Percent',
    subtitle = 'Regular Season, 2021',
    caption = 'data: nflfastr'
  ) +
  theme_538() +
  facet_wrap(vars(full_name))
```


### Predictable Offense

```{r}
expected_pass_stats <- pbp %>%
  filter(pass == 1 | rush == 1) %>%
  filter(xpass > 0.60) %>%
  filter(season == 2021) %>%
  group_by(posteam) %>%
  summarise(xp_pass_rate = mean(pass))

expected_run_stats <- pbp %>%
  filter(pass == 1 | rush == 1) %>%
  filter(xpass < 0.40) %>%
  filter(season == 2021) %>%
  group_by(posteam) %>%
  summarise(xr_run_rate = mean(rush))

expected_stats <- expected_pass_stats %>%
  left_join(expected_run_stats, by = c("posteam")) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))
```

```{r}
expected_stats %>%
  ggplot(aes(
    x = xp_pass_rate, 
    y = xr_run_rate)) +
  geom_hline(yintercept = mean(expected_stats$xr_run_rate), linetype = "dashed") +
  geom_vline(xintercept = mean(expected_stats$xp_pass_rate), linetype = "dashed") +
  geom_image(aes(image = team_logo_espn), asp = 16/9, size = 0.05) +
  theme_538() +
  labs(
    x = "Pass Rate When Expected to Pass",
    y = "Run Rate When Expected to Run",
    title = "How Predictable Each Team's Offense is"
    ) +
  scale_x_continuous(breaks = seq(0.7, 0.95, 0.05)) +
  scale_y_continuous(breaks = seq(0.55, 0.85, 0.05)) +
  annotate("text", x = 0.77, y = 0.84, label = "Run Predictable \n Pass Predictable") +
  annotate("text", x = 0.77, y = 0.6, label = "Run Unpredictable \n Pass Unpredictable") +
  annotate("text", x = 0.91, y = 0.84, label = "Run Predictable \n Pass Predictable") +
  annotate("text", x = 0.91, y = 0.6, label = "Run Unpredictable \n Pass Unpredictable")
```

### Each Team's Yards Past Sticks and YAC on 2nd and 3rd Down

```{r}
pbp_rp <- pbp %>%
  filter(!is.na(epa)) %>%
  filter(rush == 1 | pass == 1) %>%
  filter(season == 2021)

teams <- pbp %>%
  filter(season == 2021) %>%
  group_by(posteam, pass) %>%
  summarise(epa = mean(epa)) 

#teams %>% group_by(pass) %>% summarise(league_avg = mean(epa, na.rm = TRUE))

browns <- pbp_rp %>%
  filter(posteam == "CLE")
```

```{r}
browns_rec <- browns %>%
  filter(!is.na(receiver_player_name)) %>%
  group_by(defteam) %>%
  summarise(
    targets = n(),
    completion_rate = mean(complete_pass),
    adot = mean(air_yards, na.rm = TRUE),
    yac = mean(yards_after_catch, na.rm = TRUE),
    epa = mean(epa)
    ) %>%
  filter(targets >= 10)

pbp_rp <- pbp_rp %>%
  mutate(yards_past_sticks = air_yards - ydstogo)

yps <- pbp_rp %>%
  filter(!is.na(yards_past_sticks)) %>%
  filter(down %in% c(2, 3)) %>%
  group_by(posteam) %>%
  summarise(
    avg_yps = mean(yards_past_sticks),
    yps_rate = 100*mean(yards_past_sticks >= 0),
    yac = mean(yards_after_catch, na.rm = TRUE)
    ) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))
```

```{r}
yps %>%
  ggplot(aes(
    x = avg_yps, 
    y = yac)) +
  geom_smooth(method = "lm", color = "black", size = 2) +
  geom_hline(yintercept = mean(yps$yac), linetype = "dashed") +
  geom_vline(xintercept = mean(yps$avg_yps), linetype = "dashed") +
  geom_image(aes(image = team_logo_espn), asp = 16/9, size = 0.05) +
  theme_bw() +
  labs(
    x = "Average Yards Past Sticks",
    y = "Average YAC",
    title = "Each Team's Yards Past Sticks and YAC on 2nd and 3rd Down",
    subtitle = "2021 Season"
    )
```
