---
title: "R Notebook"
output: html_notebook
---

Single Season

```{r}
library(tidyverse)

pbp <- read_rds("~/Documents/nfl/data/pbp/play_by_play_2021.rds")

rosters <- read_rds("~/Documents/nfl/data/roster/roster_2021.rds")
```

## Success Rate vs. EPA of receivers

```{r}
pbp %>%
  filter(
      !is.na(receiver_player_name) & 
      play_type == "pass" & 
      down <= 4) %>%
  group_by(receiver_player_name) %>%
  summarise(
    success_rate = mean(success), 
    mean_epa = mean(epa), 
    targets = n()
    ) %>%
  filter(targets >= 100) %>%
  ggplot(aes(x = success_rate, y = mean_epa)) + 
  geom_point() + 
  geom_text_repel(aes(label = receiver_player_name)) +
  labs(
    x = "Success Rate",
    y = "EPA",
    title = "Receivers: Success Rate and EPA, Regular Season 2021", 
    subtitle = "Minimum 100 Targets",
    caption = "Data: nflfastr"
       )
```

## aDOT vs. Catch Rate

```{r}
pbp %>%
  filter(
    !is.na(receiver_player_name) & 
    play_type == "pass" & 
    down <= 4) %>%
  group_by(receiver_player_name) %>%
  summarise(
    adot = mean(air_yards), 
    targets = n(), 
    catch_rate = sum(complete_pass)/targets
    ) %>%
  filter(adot >= 5 & targets >= 100) %>%
  ggplot(aes(
    x = adot, 
    y = catch_rate)) + 
  geom_point() + 
  geom_text_repel(aes(
    label = receiver_player_name), 
    color = "grey40", 
    segment.color = "black", 
    size = 2.5) + 
  geom_smooth(method = lm, se = FALSE, linetype = "dashed", color = "black") + 
  scale_y_continuous(breaks = seq(0.4, 0.85, 0.05)) + 
  scale_x_continuous(breaks = seq(6, 20, 2)) + 
  theme_bw() + 
  labs(
    x = "aDOT", 
    y = "Catch Rate",
    title = "Catch Rate vs aDOT",
    subtitle = "Minimum 100 Targets",
    caption = "Data: nflfastr"
    )
```

## Target Share vs Air Yard Share

```{r}
market_share <- pbp %>% 
  filter(!is.na(receiver_id), play_type == "pass") %>%
  left_join(rosters, by = c('receiver_id' = 'gsis_id')) %>% 
  left_join(teams_colors_logos, by = c('posteam' = 'team_abbr')) %>% 
  filter(play_type == "pass", down <= 4) %>% 
  mutate(
    racr = yards_gained / air_yards,
    yac_oe = yards_after_catch - xyac_mean_yardage
    ) %>% 
  group_by(receiver, posteam) %>%
  mutate(
    targets = n(),
    total_airyards = sum(air_yards, na.rm = TRUE)
    ) %>% 
  group_by(posteam) %>% 
  mutate(
    team_targets = n(),
    team_airyards = sum(air_yards, na.rm = TRUE)
    ) %>% 
  group_by(receiver, posteam) %>% 
  summarise(
    targets = sum(targets, na.rm = TRUE),
    team_targets = sum(team_targets, na.rm = TRUE),
    total_airyards = sum(total_airyards, na.rm = TRUE),
    team_airyards = sum(team_airyards, na.rm = TRUE),
    target_share = (targets/team_targets)*100,
    airyards_share = (total_airyards / team_airyards)*100,
    receptions = sum(complete_pass, na.rm = TRUE),
    yards_gained = sum(yards_gained, na.rm = TRUE),
    air_yards = sum(air_yards, na.rm = TRUE),
    yards_after_catch = sum(yards_after_catch, na.rm = TRUE),
    adot = air_yards / targets,
    yac_oe = mean(yac_oe, na.rm = TRUE), ### Yards After Catch Over Expected
    racr = yards_gained / air_yards, ### Receiver Air Yard Conversion Ratio
    xyac_epa = sum(xyac_epa, na.rm = TRUE),
    xyac_mean_yardage = mean(xyac_mean_yardage, na.rm = TRUE), ### Mean Expected Yards After Catch
    xyac_median_yardage = mean(xyac_median_yardage, na.rm = TRUE),
    xyac_success = mean(xyac_success, na.rm = TRUE),
    xyac_fd = mean(xyac_fd, na.rm = TRUE),
    ep = mean(ep),
    total_epa = sum(epa),
    epa_target = total_epa / targets,
    epa_reception = total_epa / receptions) %>% 
  filter(!is.na(receiver), xyac_mean_yardage > 0, targets > 100) %>% 
  left_join(teams_colors_logos, by = c('posteam' = 'team_abbr')) 
```

```{r}
market_share %>%
  ggplot(aes(
    x = target_share, 
    y = airyards_share, 
    size = targets,
    fill = team_color,
    colour = team_color2)) +
  geom_point(shape = 21, alpha = 0.8) +
  geom_label_repel(aes(label = receiver), fill = "white", size = 3) +
  scale_color_identity(aesthetics = c('fill', 'colour')) +
  labs(
    title = "Target Share vs Air Yard Share - 2020 Season",
    subtitle = "Bubble Size = Total Targets (min. 100 targets)",
    caption = "Data: nflfastR",
    y = "Air Yards Share",
    x = "Target Share"
    ) + 
  theme(
    legend.position = "none",
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "light grey"),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 18),
    axis.text = element_text(size = 12),
    panel.border = element_rect(color = "black", fill = NA)
    )
```

## WR Catch Rate by aDoT

```{r}
rosters <- purrr::map_df(c(2016:2021), function(x) {
  readRDS(
      glue::glue("~/Documents/nfl/data/roster/roster_{x}.rds")
    )
})

data_clean <- pbp %>%
  filter(
    pass == 1 & sack == 0 & qb_scramble == 0, 
    !is.na(receiver_jersey_number)
    ) %>%
  select(
    name, pass, desc, posteam, epa, defteam, complete_pass, incomplete_pass,
    air_yards, receiver_player_name, receiver_jersey_number, down, success, complete_pass
  ) %>%
  left_join(rosters, by = c("receiver_jersey_number" = "jersey_number", "posteam" = "team")) %>% 
  filter(!is.na(position)) %>% 
  mutate(position = if_else(position == "FB", "RB", position))

pos <- data_clean %>%
  filter(position != "QB") %>% 
  mutate(position = factor(position, levels = c("WR", "RB", "TE")))

pass_comp <- pos %>%
  filter(between(air_yards, 1, 25)) %>%
  group_by(position, air_yards) %>%
  summarise(
    n = n(),
    comp_rate = sum(complete_pass, na.rm = TRUE) / n,
    epa = mean(epa, na.rm = TRUE)
  ) %>% 
  na.omit()
```

```{r}
pass_comp %>%
  filter(position == "WR") %>%
  ggplot(aes(
    x = air_yards, 
    y = comp_rate, 
    fill = position)) +
  geom_point(aes(size = n), shape = 21, stroke = 0.5) +
  geom_smooth(color = "white", method = "loess") +
  geom_hline(yintercept = 0, size = 1, color = "black") +
  geom_vline(xintercept = 20, size = 1, color = "black", linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = 0.5, size = 1, color = "black", linetype = "dashed", alpha = 0.5) +
  facet_grid(~position) +
  scale_fill_manual(
    values = c("#00b159", "#003399", "#ff2b4f"),
    aesthetics = c("color", "fill")
  ) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x = "Air Yards (Depth of Target)",
    y = "Completion Rate \n",
    title = "Completion rate by Depth of Target on 1st/2nd Down",
    subtitle = "Completion rate generally drops below 50% for passes > 20 air yards",
    caption = "Data: nflfastR",
    size = "N of Passes"
  ) +
  guides(color = "none", fill = "none") +
  theme(
    strip.text = element_text(face = "bold"),
    legend.direction = "vertical",
    legend.position = c(0.1, 0.2),
    legend.background = element_blank(),
    legend.title = element_text(face = "bold")
  )
```


```{r}
pbp <- purrr::map_df(c(2016:2021), function(x) {
  readRDS(
      glue::glue("~/Documents/nfl/data/pbp/play_by_play_{x}.rds")
    )
})

rosters <- purrr::map_df(c(2016:2021), function(x) {
  readRDS(
      glue::glue("~/Documents/nfl/data/roster/roster_{x}.rds")
    )
})
```

## aDot vs XYAC EPA

```{r}
wrs1 <- pbp %>%
  filter(season_type == "REG", !is.na(epa)) %>%
  group_by(id, receiver_player_name) %>%
  summarise(
    air_wpa = mean(air_wpa, na.rm = TRUE),
    yac_wpa = mean(yac_wpa, na.rm = TRUE),
    adot = mean(air_yards, na.rm = TRUE),
    xyac_epa = mean(xyac_epa, na.rm = TRUE),
    n_dropbacks = sum(pass),
    n_plays = n(),
    team = last(posteam)
  ) %>%
  ungroup() %>%
  filter(n_plays > 100) %>%
  left_join(teams_colors_logos, by = c('team' = 'team_abbr'))
```

```{r}
wrs1 %>%
  filter(!is.na(receiver_player_name)) %>%
  ggplot(aes(
    x = adot, 
    y = xyac_epa, 
    colour = team_color
    )) +
  geom_point(aes(size = n_plays), alpha = .6) +
  geom_text_repel(aes(label = receiver_player_name)) +
  scale_color_identity(aesthetics = c('fill', 'colour')) +
  theme_minimal() +
  labs(
    x = "aDoT",
    y = "xYAC EPA",
    title = "WR Efficiency, 2016 - 2021",
    caption = "Data: nflfastR",
    size = "n Plays"
    ) +
  theme(plot.title = element_text(size = 14, hjust = 0.5, face = "bold")) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))
```



