---
title: "R Notebook"
output: html_notebook
---

```{r}
spreadspoke_scores <- read_csv("Downloads/nfl_spread/spreadspoke_scores.csv", 
    col_types = cols(schedule_date = col_date(format = "%m/%d/%Y"), 
        schedule_season = col_number()))
```

```{r}
point_prob <- point_prob[-2,] #no lines have 0.5

eh <- sort(my_df %>% distinct(spread_favorite) %>% pull(), decreasing = TRUE)
point_prob$point_spread
point_prob$favourite_win_prob



fav_win_prob = case_when(
  spread_favorite == 0 ~ 50.0,
  spread_favorite == 1 ~ 51.3,
  spread_favorite == 1.5 ~ 52.5,
  spread_favorite == 2 ~ 53.5,
  spread_favorite == 2.5 ~ 54.5,
  spread_favorite == 3 ~ 59.4,
  spread_favorite == 3.5 ~ 64.3,
  spread_favorite == 4 ~ 65.8,
  spread_favorite == 4.5 ~ 67.3,
  spread_favorite == 5 ~ 68.1,
  spread_favorite == 5.5 ~ 69,
  spread_favorite == 6 ~ 70.7,
  spread_favorite == 6.5 ~ 72.4,
  spread_favorite == 7 ~ 75.2,
  spread_favorite == 7.5 ~ 78.1,
  spread_favorite == 8 ~ 79.1,
  spread_favorite == 8.5 ~ 80.2,
  spread_favorite == 9 ~ 80.7,
  spread_favorite == 9.5 ~ 81.1,
  spread_favorite == 10 ~ 83.6,
  spread_favorite == 10.5 ~ 86,
  spread_favorite == 11 ~ 87.1,
  spread_favorite == 11.5 ~ 88.2,
  spread_favorite == 12 ~ 88.5,
  spread_favorite == 12.5 ~ 88.7,
  spread_favorite == 13 ~ 89.3,
  spread_favorite == 13.5 ~ 90,
  spread_favorite == 14 ~ 92.4,
  spread_favorite == 14.5 ~ 94.9,
  spread_favorite == 15 ~ 95.6,
  spread_favorite == 15.5 ~ 96.3,
  spread_favorite == 16 ~ 98.1,
  spread_favorite == 16.5 ~ 99.8,
  spread_favorite >= 17 ~ 100
)


my_df <- my_df %>%
  mutate(
    fav_win_prob = case_when(
      spread_favorite == 0 ~ 50.0,
      spread_favorite == -1 ~ 51.3,
      spread_favorite == -1.5 ~ 52.5,
      spread_favorite == -2 ~ 53.5,
      spread_favorite == -2.5 ~ 54.5,
      spread_favorite == -3 ~ 59.4,
      spread_favorite == -3.5 ~ 64.3,
      spread_favorite == -4 ~ 65.8,
      spread_favorite == -4.5 ~ 67.3,
      spread_favorite == -5 ~ 68.1,
      spread_favorite == -5.5 ~ 69,
      spread_favorite == -6 ~ 70.7,
      spread_favorite == -6.5 ~ 72.4,
      spread_favorite == -7 ~ 75.2,
      spread_favorite == -7.5 ~ 78.1,
      spread_favorite == -8 ~ 79.1,
      spread_favorite == -8.5 ~ 80.2,
      spread_favorite == -9 ~ 80.7,
      spread_favorite == -9.5 ~ 81.1,
      spread_favorite == -10 ~ 83.6,
      spread_favorite == -10.5 ~ 86,
      spread_favorite == -11 ~ 87.1,
      spread_favorite == -11.5 ~ 88.2,
      spread_favorite == -12 ~ 88.5,
      spread_favorite == -12.5 ~ 88.7,
      spread_favorite == -13 ~ 89.3,
      spread_favorite == -13.5 ~ 90,
      spread_favorite == -14 ~ 92.4,
      spread_favorite == -14.5 ~ 94.9,
      spread_favorite == -15 ~ 95.6,
      spread_favorite == -15.5 ~ 96.3,
      spread_favorite == -16 ~ 98.1,
      spread_favorite == -16.5 ~ 99.8,
      spread_favorite <= -17 ~ 100
      )
    )

spreadspoke_scores



```


```{r}
my_df <- spreadspoke_scores %>%
  select(
    home = team_home,
    away = team_away,
    date = schedule_date,
    year = schedule_season,
    spread_favorite, team_favorite_id
  ) %>%
  filter(!is.na(spread_favorite))

my_df %>% 
  mutate(
    if_else(spread_favorite ==)
  )
```


```{r}
spreadspoke_scores %>%
  filter(
    schedule_season >= 2000 &
    !is.na(spread_favorite))
```

```{r}
point_prob <- read_csv("Downloads/nfl_spread/point_prob - Sheet1.csv", 
    col_types = cols(point_spread = col_number(), 
        favourite_win_prob = col_number(), 
        underdog_win_prob = col_number()))

point_prob
```

```{r}
ggplot(point_prob) +
  aes(x = point_spread, y = favourite_win_prob) +
  geom_line(size = 0.5, colour = "#FF9595") +
  labs(x = "Point Spread", y = "Favourite Win Probability") +
  scale_x_continuous(breaks = seq(0, 17, 1)) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  hrbrthemes::theme_ft_rc()
```



