---
title: "R Notebook"
output: html_notebook
---

### Each Team's Difference Between Pass and Rush YPP Table 

```{r}
pbp_rp <- pbp %>%
  filter(!is.na(epa)) %>%
  filter(rush == 1 | pass == 1) %>%
  filter(season == 2021)

#now let's see which teams have the biggest difference between their passing and running
pass_stats <- pbp_rp %>%
  filter(!is.na(yards_gained)) %>% 
  filter(!is.na(pass_oe)) %>%
  filter(pass == 1) %>%
  group_by(posteam) %>%
  summarise(pass_ypp = mean(yards_gained)) 

run_stats <- pbp_rp %>%
  filter(!is.na(yards_gained)) %>% 
  filter(rush == 1) %>%
  group_by(posteam) %>% 
  summarize(run_ypp = mean(yards_gained))

#this time since we did group_by with posteam both times it'll join automatically
pass_run_stats <- pass_stats %>%
  left_join(run_stats)

pass_run_stats <- pass_run_stats %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

pass_run_stats <- pass_run_stats %>%
  mutate(pass_minus_run = pass_ypp - run_ypp) %>%
  arrange(desc(pass_minus_run)) %>% #putting the teams with the biggest diff at the top
  mutate(rank = row_number())

tab_data <- pass_run_stats %>%
  select(rank, team_wordmark, pass_ypp, run_ypp, pass_minus_run)

tab_data <- tab_data %>%
  mutate_if(is.numeric, ~round(., 1))
```

```{r}
ypp_diff <- tab_data %>% 
  gt() %>% 
  text_transform(
    locations = cells_body(c(team_wordmark)),
    fn = function(x){
      web_image(
        url = x,
        height = px(20)
      )
    }
  ) %>% 
  cols_label(
    rank = "Rank",
    team_wordmark = "Team",
    pass_ypp = "Pass YPP",
    run_ypp = "Rush YPP",
    pass_minus_run = "Diff.") %>%
  data_color(
    columns = c(pass_minus_run),
    colors = scales::col_numeric(
      palette = c("#af8dc3", "#f7f7f7", "#7fbf7b"),
      domain = c(0, 3.5)
    )
  ) %>% 
  tab_header(
    title = "Each Team's Difference Between Pass and Rush YPP",
    subtitle = "YPP = Yards per Play"
  ) %>%
  tab_options(
    column_labels.background.color = "white",
    column_labels.font.weight = "bold",
    table.border.top.width = px(3),
    table.border.bottom.width = px(3),
    column_labels.border.top.width = px(3),
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    data_row.padding = px(3),
    source_notes.font.size = 12,
    table.font.size = 16,
    heading.align = "middle",
  ) %>%
  opt_table_font(
    font = list(
      default_fonts()
    )
  ) 
```

```{r}
ypp_diff
```

