---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

pbp <- purrr::map_df(c(2016:2021), function(x) {
  read_rds(
    glue::glue("~/Documents/nfl/data/pbp/play_by_play_{x}.rds")
  )
}) %>%
  filter(season_type == 'REG')
```

```{r height_function}
height_to_cm <- function(x) {
  # this is to convert a character string of height to cm
  # e.g. "6-4" will convert to 193.04 as a numerical
  
  #can cheat here since it is unlikely that 10 feet will be used
  feet = substr(x, 1, 1) %>% as.numeric()
  inches = substr(x, 3, 4) %>% as.numeric()
  cm = (feet * 30.48) + (inches * 2.54)
  return(cm)
}
```

```{r}
rosters <- purrr::map_df(c(2016:2021), function(x) {
  read_rds(
    glue::glue("~/Documents/nfl/data/roster/roster_{x}.rds")
  )
})

rosters <- rosters %>%
  filter(position %in% c("RB", "WR", "TE", "FB")) %>%
  mutate(
    height = height_to_cm(height),
    weight = weight %>% as.numeric(),
    age = format(Sys.time(), "%Y") %>% as.numeric() - lubridate::year(birth_date), .after = weight,
    status = as_factor(status)
  ) %>%
  select(-c(
    depth_chart_position:jersey_number, birth_date, 
    first_name:last_name, college:high_school, 
    espn_id:pff_id, fantasy_data_id:sportradar_id))
```

```{r}
ngs_receiving <- read_rds("~/Documents/nfl/data/ngs/ngs_receiving.rds") %>% 
  filter(season_type == 'REG') %>% 
  select(-season_type)

#group by week
ngs_receiving_week <- ngs_receiving %>%
  filter(!week == 0) %>%
  select(-c(player_first_name:player_jersey_number)) %>%
  left_join(rosters, by = c("player_gsis_id" = "gsis_id", "season" = "season")) %>%
  mutate(player_label = paste0(player_display_name, ", ", "Week ", week, ", ", season)) %>%
  distinct(player_label, .keep_all = TRUE)

#group by season
ngs_receiving_season <- ngs_receiving %>%
  filter(week == 0) %>%
  select(-week) %>%
  left_join(rosters, by = c("player_gsis_id" = "gsis_id", "season" = "season")) %>%
  mutate(player_label = paste0(player_display_name, ", ", season)) %>%
  distinct(player_label, .keep_all = TRUE)

write_rds(ngs_receiving_season, "ngs_receiving_season.rds")


ngs_receiving_season <- ngs_receiving_season %>%
  left_join(rosters, by = c("player_gsis_id" = "gsis_id", "season" = "season")) 

```


```{r}
snap_counts <- purrr::map_df(c(2016:2021), function(x) {
  read_csv(
    glue::glue("~/Documents/nfl/data/snap_count/snap_count_{x}.csv")
  )
}) %>%
  filter(game_type == 'REG', position %in% c("RB", "WR", "TE", "FB"))


ngs_receiving_week <- ngs_receiving_week %>%
  left_join(
    snap_counts %>%
  select(-c(game_id, pfr_game_id, game_type, starts_with(c('defense_', 'st_')))), by = c(
    "pfr_id" = "pfr_player_id", "season" = "season", "week" = "week", "position" = "position", "team" = "team", "player_display_name" = "player")
  )

rm(snap_counts)

write_rds(ngs_receiving_week, "ngs_receiving_week.rds")
```

```{r}
ngs_receiving_week <- read_rds("~/Documents/Github/nfl/pca/ngs_receiving_week.rds")
ngs_receiving_season <- read_rds("~/ngs_receiving_season.rds")
rec_stats <- read_rds("~/Desktop/rec_stats_full.rds")
rec_stats2 <- read_rds("~/wr_stats_full1.rds")
rec_stats3 <- read_rds("~/wr_stats_full2.rds")
```

```{r}
rec_stats %>% names()
```

```{r}
wr_stats <- ngs_receiving_season %>%
  left_join(
    rec_stats3, by = c("player_gsis_id" = "receiver_id", "position" = "position", "season" = "season")
  )

wr_stats <- wr_stats %>% select(-c(posteam, team, player_short_name, player_jersey_number, player_last_name, player_first_name))

write_rds(wr_stats, "rec_stats.rds")
```


```{r}
rec_stats3

ngs_receiving_season %>%
  inner_join(
    rec_stats3, by = c("player_gsis_id" = "receiver_id", "season" = "season")
  )
```

```{r}
ngs_receiving_season
```

```{r}
#see if you can match them

ngs_receiving_season %>%
  group_by(season) %>%
  filter(gsis_id %in% rec_stats3[["receiver_id"]])
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

