---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

pbp <- purrr::map_df(c(2000:2021), function(x) {
  readRDS(
      glue::glue("~/Documents/nfl/data/pbp/play_by_play_{x}.rds")
    )
}) %>%
  filter(season_type == 'REG')
```

```{r}
fourth_and_short <- pbp %>%
  filter(down == 4 & ydstogo <= 4 & !play_type %in% c('no_play', 'qb_kneel', NA))

#rm(pbp) because it's huge
```

```{r}
fourth_and_short1 <- fourth_and_short %>%
  select(week, season, posteam, yardline_100, down, 
         ydstogo, play_type, yards_gained, wpa, 
         fourth_down_converted, fourth_down_failed)

fourth_and_short_summary <- fourth_and_short1 %>%
  group_by(season) %>%
  count(play_type) %>%
  mutate(prop = n/sum(n)) %>%
  ungroup()
```


```{r}
ggplot(fourth_and_short_summary) +
  aes(x = season, y = prop, colour = play_type) +
  geom_line(size = 1L) +
  scale_color_brewer(palette = "Dark2", direction = 1) +
  hrbrthemes::theme_ft_rc()
```

```{r}
fourth_df <- fourth_and_short1 %>%
  group_by(season, play_type) %>%
  summarise(
    n = n(),
    n_converted = sum(fourth_down_converted),
    n_failed = sum(fourth_down_failed)
  ) %>%
  mutate(prop = n/sum(n), .after = n) %>%
  ungroup()
```

```{r}
fourth_df %>%
  group_by(season) %>%
  tally(n)

fourth_df %>%
  group_by(season) %>%
  summarise(
    total_failed = sum(n_failed),
    total_converted = sum(n_converted),
    total_attempted = sum(n_converted, n_failed)
  )
```

```{r}
fourth_df_down <- fourth_and_short1 %>%
  group_by(season, play_type, ydstogo) %>%
  summarise(
    n = n(),
    n_converted = sum(fourth_down_converted),
    n_failed = sum(fourth_down_failed)
  ) %>%
  mutate(prop = n/sum(n), .after = n) %>%
  ungroup()
```

```{r}

#fourth_df_down %>% mutate(season = str_sub(season, 2, -2)) #str_sub(c("2000", "2001"), 3, 4)

library(scales)

fourth_df_down %>%
  ggplot(aes(x = season_f, y = prop, colour = play_type)) +
  geom_line(size = 0.9) +
  scale_color_brewer(palette = "Dark2", direction = 1) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  scale_x_continuous(breaks = seq(2000, 2021, 2)) +
  labs(
    x = " ",
    y = "Proportion",
    title = "Proportion of Play Call on 4th and Short",
    color = "Play Type"
  ) +
  hrbrthemes::theme_ft_rc() +
  facet_wrap(~ydstogo)
```


```{r}
fourth_df_down1 <- fourth_df_down %>%
  group_by(season, ydstogo) %>%
  summarise(
    total_failed = sum(n_failed),
    total_converted = sum(n_converted),
    total_attempted = sum(n_converted, n_failed)
  )
```



