---
title: "R Notebook"
output: html_notebook
---

```{r}
suppressPackageStartupMessages()
library(dplyr)
library(bayesboot)
library(ggplot2)

# Read and mutate data
pbp <- purrr::map_df(c(2016:2020), function(x) {
  readRDS(
    glue::glue("~/Documents/nfl/data/pbp/play_by_play_{x}.rds")
  )
})
```

```{r}
# Prepare data frame
pbp <- pbp %>%
  filter(
    season_type == "REG",
    play_type %in% c("pass"),
    !is.na(epa),
    !is.na(name)
  ) %>%
  group_by(passer_player_id) %>%
  mutate(num_plays = n()) %>%
  ungroup() %>%
  filter(num_plays >= 120)
```

## Bootstrapping

```{r}
# Here you will use your data and RYOE instead of EPA
lst <- list()
qbs <- pull(pbp, name) %>% unique() #qbs <- unique(pbp$name)

for (qb in qbs) {
  pbp_qb <- pbp %>% filter(name == qb)
  b <- bayesboot(as.vector(pbp_qb$epa), mean)
  s <- summary(b)
  mean_epa <- s$value[1]
  lci <- s$value[3]
  uci <- s$value[4]
  df <- data.frame("mean" = mean_epa, "LCI" = lci, "UCI" = uci)
  lst[[qb]] <- df
}
```

```{r}
df <- dplyr::bind_rows(lst) %>% 
  mutate(QB = qbs) %>% 
  arrange(mean)
```

### Plot
```{r}
df %>%
  ggplot(aes(
    x = factor(QB, level = QB), 
    y = mean
    )) +
  geom_pointrange(aes(
    ymin = (LCI),
    ymax = (UCI)
  )) +
  coord_flip() +
  theme_bw()
```

## Looking at Specific Players
```{r}
# You can do a whole lot of things with this code for example:
lst <- list()
qbs <- c("D.Prescott", "J.Goff", "C.Wentz")
for (qb in qbs) {
  pbp_qb <- filter(pbp, name == qb)
  b <- bayesboot(pull(pbp_qb, epa), mean)
  df <- data.frame(
    "estimate" = pull(b, V1), 
    "QB" = qb, 
    team_abbr = unique(pull(pbp_qb, posteam))
    )
  
  lst[[qb]] <- df
}
```

```{r}
df <- dplyr::bind_rows(lst)
colors <- nflfastR::teams_colors_logos %>% 
  filter(team_abbr %in% c("DAL", "LA", "PHI"))

df %>% 
  ggplot(aes(
    x = estimate
    )) +
  geom_density(aes(fill = QB), alpha = .6) +
  scale_fill_manual(
    values = c(colors$team_color[3], colors$team_color[1], colors$team_color2[2])
  ) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 14),
    plot.subtitle = element_text(size = 13),
    axis.title.y = element_blank()
  ) +
  labs(
    title = "Bayesian Bootstrapping to estimate range of possible outcomes for QB class of 2016.",
    subtitle = "Regular Season. 2016 - 2020. Passing plays only.",
    x = "Passing Efficiency"
  ) 
```

