---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(na.tools)
library(lme4) 
library(broom.mixed) 
library(ggplot2)
library(tidyr) 
library(plm) 


data <- purrr::map_df(c(2016:2021), function(x) {
  readRDS(
    glue::glue("~/Documents/nfl/data/pbp/play_by_play_{x}.rds")
  )
})
```

```{r}
dataraw <- data %>%
  filter(
    play_type %in% c("run", "pass"),
    penalty == 0,
    season_type == "REG",
    !is.na(down),
    !is.na(yardline_100)
  ) %>%
  mutate(
    in_red_zone = if_else(yardline_100 <= 20, 1, 0),
    in_fg_range = if_else(yardline_100 <= 35, 1, 0),
    run = if_else(play_type == "run", 1, 0),
    pass = if_else(play_type == "pass", 1, 0)
  )

prev_play <- dataraw %>%
  group_by(game_id, posteam) %>%
  mutate(
    total_runs = if_else(play_type == "run", cumsum(run) - 1, cumsum(run)),
    total_pass = if_else(play_type == "pass", cumsum(pass) - 1, cumsum(pass)),
    previous_play = if_else(posteam == dplyr::lag(posteam), dplyr::lag(play_type), "First play of Drive"),
    previous_play = if_else(is.na(previous_play), replace_na("First play of Drive"), previous_play)
  )
```

```{r}
data_filt <- prev_play %>%
  filter(
    !is_na(epa),
    !is.na(down),
    !is_na(passer_player_name),
    play_type == "pass"
  )

epa_data <- data_filt %>%
  select(
    game_id, play_id, epa, yac_epa, air_epa, ep, posteam, defteam, season,
    passer_player_name, complete_pass, yardline_100, ydstogo, down, quarter_seconds_remaining,
    half_seconds_remaining, game_seconds_remaining, yards_after_catch, air_yards, qb_hit,
    home_team, away_team, roof, desc, sack, qb_hit, yards_gained, previous_play, qtr, score_differential
  ) %>%
  mutate(
    down = as.factor(down),
    under2minute = if_else(half_seconds_remaining < 120, 1, 0),
    half_seconds_remaining = scale(half_seconds_remaining),
    t = paste(season, game_id, play_id, sep = ""),
    posid = paste(home_team, away_team, as.character(season), posteam, sep = ""),
    defid = paste(home_team, away_team, as.character(season), defteam, sep = ""),
    t = paste(season, game_id, play_id),
    away = if_else(home_team == posteam, 0, 1),
    outdoor = if_else(roof == "OUTDOOR", 1, 0),
    roof = as.factor(roof),
    log_ydstogo = log(ydstogo),
    t = paste(play_id, game_id, season),
    converted = if_else(yards_gained - ydstogo > 0, 1, 0),
    prev_play_run = if_else(previous_play == "run", 1, 0),
    quarter4 = if_else(qtr == 4, 1, 0),
    first_play_drive = if_else(previous_play == "First play of Drive", 1, 0)
  )
```

```{r}
plays_qb <- epa_data %>%
  group_by(passer_player_name) %>%
  summarise(
    num_plays = n()
  )
colnames(plays_qb)[1] <- "level"

mixed <- lmer(epa ~
yardline_100 +
  ydstogo +
  down +
  ydstogo * down +
  half_seconds_remaining +
  quarter4 +
  quarter4 * down +
  score_differential +
  away +
  outdoor +
  # def_COV*pos_RECV + (remember this is not public)
  (1 | passer_player_name),
data = epa_data
)
```

```{r}
tt <- broom.mixed::tidy(mixed, effects = "ran_vals") %>%
  merge(plays_qb, by = "level", all.x = TRUE, no.dups = TRUE) %>%
  filter(num_plays > 500) %>%
  mutate(
    QB = as.factor(level),
    t_stat = estimate / std.error
  )

tt <- tt[order(-tt$estimate), ]
tt <- head(tt, n = 32)
z <- 1.96
tt <- tt %>% 
  filter(abs(t_stat) > z)
```

```{r}
tt <- tt[order(tt$estimate), ]

tt %>%
  ggplot(aes(
    x = factor(QB, level = QB),
    estimate
  )) +
  geom_point() +
  geom_pointrange(aes(
    ymin = estimate - z * std.error,
    ymax = estimate + z * std.error
  )) +
  coord_flip() +
  theme_bw() +
  labs(
    x = "Quarterback",
    y = "Random-effects estimate | EPA/play",
    caption = "Data: nflfastR",
    title = "Extra EPA/play generated by QB on Passing Plays",
    subtitle = paste(2016, "to", 2021, ", Regular Season")
  )
```

